esphome:
  name: weather_station

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret psw

ota:
  safe_mode: true
  password: !secret psw

wifi:
  ssid: "Casa"
  password: !secret wifi_psw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather Station Fallback Hotspot"
    password: "zkhTAyEVQ2j4"

captive_portal:

# I2C
i2c:
  sda: D1
  scl: D2
  scan: true
