esphome:
  name: weather_station

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
# api:
#  password: !secret psw

ota:
  safe_mode: true
  password: !secret psw

wifi:
  ssid: "Casa"
  password: !secret wifi_psw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather Station Fallback Hotspot"
    password: "zkhTAyEVQ2j4"

captive_portal:

# MQTT
mqtt:
  broker: 192.168.1.7
  username: mqtt_user
  password: !secret mqtt_psw

# I2C
i2c:
  sda: D2
  scl: D1
  scan: true

sensor:
  # BME 280
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: temperature
    pressure:
      name: "BME280 Pressure"
      id: pressure
    humidity:
      name: "BME280 Humidity"
      id: humidity
    address: 0x76
    update_interval: 30s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ip

font:
  - file: "gfonts://Lato"
    id: lato
    size: 15

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(lato), "Wifi: %s", id(ip).state.c_str());
      it.printf(0, 15, id(lato), "Temp: %.1f°C", id(temperature).state);
      it.printf(0, 30, id(lato), "Hum: %.1f%%", id(humidity).state);
      it.printf(0, 45, id(lato), "Press: %.1fhpa", id(pressure).state);

interval:
  - interval: 30s
    then:
      - mqtt.publish_json:
          topic: weatherstation/live
          payload: |-
            root["outTemp"] = id(temperature).state;
            root["outHumidity"] = id(humidity).state;
            root["pressure"] = id(pressure).state;
